from .workflow_guide_node import (
    NODE_CLASS_MAPPINGS as GUIDE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GUIDE_NODE_DISPLAY_NAME_MAPPINGS
)

from .workflow_documentation_panel_node import (
    NODE_CLASS_MAPPINGS as PANEL_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PANEL_NODE_DISPLAY_NAME_MAPPINGS
)

NODE_CLASS_MAPPINGS = {}

NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(
    GUIDE_NODE_CLASS_MAPPINGS
)

NODE_CLASS_MAPPINGS.update(
    PANEL_NODE_CLASS_MAPPINGS
)

NODE_DISPLAY_NAME_MAPPINGS.update(
    GUIDE_NODE_DISPLAY_NAME_MAPPINGS
)

NODE_DISPLAY_NAME_MAPPINGS.update(
    PANEL_NODE_DISPLAY_NAME_MAPPINGS
)

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS"
]